### ISSUE TITLE
Not a issue but a doubt

### ISSUE THREAD

**Issue by iamharshit** [NicoHood/PinChangeInterrupt#10]
can we use the new interrupt pins (we got by using pinchangeinterrupt ) only for external interrupt or it can be used for timer interrupt too?

**Comment by NicoHood** [comment]
Isn't this something completely different? Its used for external interrupts like the normal pin interrupts.
I have too less knowledge yet about timers, so you better ask in the arduino forum/chat.

**Comment by iamharshit** [comment]
just tricking you.
