### ISSUE TITLE
PB6 and PB7

### ISSUE THREAD

**Issue by geologic** [NicoHood/PinChangeInterrupt#22]
Hi

I'm using a 328P on a breadboard and i set PB6 and PB7 as a digital I/O pins. I tested with a led and they are working ok.
Now i want to use those pins with PinChangeInterrupt, but they don't respond to changes. I read that i need to enable those pins on PinChangeInterruptSettings.h, but i don't know how to do it.
Can you please help?

Thanks

**Comment by NicoHood** [comment]
Remove this:
https://github.com/NicoHood/PinChangeInterrupt/blob/master/src/PinChangeInterruptSettings.h#L123-L128

**Comment by geologic** [comment]
I comented those lines, but no luck... 
They still don't respond to changes.

**Comment by NicoHood** [comment]
Did you try PB5?

**Comment by NicoHood** [comment]
Hm I dont know why.

**Comment by geologic** [comment]
I found the problem. This is my original code: 

```
#define XTAL2 20     //XTAL is D20
attachPCINT(digitalPinToPCINT(XTAL2), Detected, CHANGE);
```

This doesn't work, but the following does:

`attachPCINT(6, Detected, CHANGE);`

So the problem is in your digitalPinToPCINT() doesn't map PB6 to IDE pin 20

**Comment by NicoHood** [comment]
Okay, thanks for your help here. I am not sure if pin 20 is officially mapped to the XTAL2, is it? Maybe we could fix the macro?

**Comment by geologic** [comment]
Well, i followed this to add support for XTAL1/XTAL2 as D20 / D21

[](http://web.archive.org/web/20130524110602/http://placeboaudio.com/how-tu-use-atmega-pb6-pb7-with-arduino-when-n)

So, i think is not official.

**Comment by NicoHood** [comment]
Well then it is expected. I suggest using the direct PCINT number if you are using such an uncommon scenario. thanks for the feedback :)
