### ISSUE TITLE
PORT NAMES

### ISSUE THREAD

**Issue by tomaskovacik** [NicoHood/PinChangeInterrupt#24]
hello, 

is there any reason why did not have port names corresponding with datasheet?

PORTA,PORTB...

I have to grep PCINT10 in whole src directory to find out that it is in port1 so I can disable port0,port2 and port3

**Comment by NicoHood** [comment]
Because on some MCUs PORTA is not always a PCINT port.

**Comment by tomaskovacik** [comment]
Oh I got it,  pcmsk  registers are numbered 0,1.... now it make sens, thx!
