### ISSUE TITLE
multiple definition of `__vector_3'

### ISSUE THREAD

**Issue by geologic** [NicoHood/PinChangeInterrupt#25]
Hi

I'm using your library to detect a change on PCINT=7 (xtal pin) and it is working.
Later i added neoSWSerial library to comunicate on pins D7 and D8, and i got this error when compiling.

multiple definition of `__vector_3'

In this related issue [you](https://github.com/NicoHood/PinChangeInterrupt/issues/14#issuecomment-300781984) say it is possible to have both libraries working, but i don't know where to modify.

Can you please help?

**Comment by NicoHood** [comment]
You better use a real Serial than softserial. Get the right board for you usecase. You cannot use a PCINT library if the other library uses them as well. Or use normal interrupts.
