### ISSUE TITLE
on pc level change interrupt, disable/enable not working

### ISSUE THREAD

**Issue by geetee24** [NicoHood/PinChangeInterrupt#29]
on uno,  d2, i trigger interrupt on level going falling.
in my int handler, I call 	disablePinChangeInterrupt ( digitalPinToPinChangeInterrupt ( 2 ) );
and then my loop() comes alive.
all is well.

however, if i press my button which triggers int handler TOO fast,  I see that the int handler is called BUT the Loop() is never called.

Any ideas?

**Comment by NicoHood** [comment]
Can you please send in a minimal example to reproduce the issue? I have no idea what you are talking about, to be honest.
