### ISSUE TITLE
Support of ATmega644 not only ATmega644P

### ISSUE THREAD

**Issue by roboticboyer** [NicoHood/PinChangeInterrupt#34]
Please add the support of ATmega644 not only ATmega644P

https://github.com/NicoHood/PinChangeInterrupt/blob/f1b1632a8b4cf7a177626d8baaed6d23fdf12552/src/PinChangeInterruptBoards.h#L94

The patched code is:
`#elif defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega644P__) || defined(__AVR_ATmega644__)`

Thank you
Gio

**Comment by NicoHood** [comment]
Thanks, I've added the support here:
https://github.com/NicoHood/PinChangeInterrupt/commit/771983ccf3a65e673f737d762bf162733fc95e72

**Comment by NicoHood** [comment]
Added with release 1.2.8
